robotic_arm_v3:
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - twist_1
      - rev_1
      - rev_2
      - twist_2
      - rev_3
      - twist_3

  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50