robot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - twist_1
    - rev_1
    - rev_2
    - twist_2
    - rev_3
    - twist_3
  gains:
    twist_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    twist_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    twist_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1